./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/97_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_970011_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 97_11.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/97_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_970012_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 97_12.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/97_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_970021_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 97_21.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/97_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_970022_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 97_22.las


./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/83_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_830011_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 83_11.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/83_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_830012_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 83_12.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/83_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_830021_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 83_21.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/83_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_830022_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 83_22.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/87_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_870011_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 87_11.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/87_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_870012_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 87_12.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/87_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_870021_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 87_21.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/87_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_870022_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 87_22.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/85_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_850011_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 85_11.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/85_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_850012_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 85_12.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/85_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_850021_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 85_21.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/85_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_850022_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 85_22.las


./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/84_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_840011_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 84_11.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/84_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_840012_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 84_12.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/84_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_840021_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 84_21.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/84_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_840022_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 84_22.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/62_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_620011_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 62_11.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/62_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_620012_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 62_12.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/62_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_620021_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 62_21.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/62_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_620022_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 62_22.las


./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/49_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_490011_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 49_11.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/49_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_490012_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 49_12.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/49_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_490021_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 49_21.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/49_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_490022_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 49_22.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/47_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_470011_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 47_11.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/47_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_470012_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 47_12.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/47_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_470021_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 47_21.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/47_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_470022_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 47_22.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/32_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_320011_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 32_11.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/32_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_320012_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 32_12.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/32_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_320021_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 32_21.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/32_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_320022_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 32_22.las


./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/31_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_310011_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 31_11.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/31_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_310012_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 31_12.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/31_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_310021_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 31_21.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/31_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_310022_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 31_22.las


./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/29_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_290011_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 29_11.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/29_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_290012_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 29_12.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/29_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_290021_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 29_21.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/29_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_290022_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 29_22.las


./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/27_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_270011_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 27_11.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/27_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_270012_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 27_12.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/27_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_270021_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 27_21.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/27_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_270022_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 27_22.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/150_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_1500011_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 150_11.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/150_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_1500012_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 150_12.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/150_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_1500021_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 150_21.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/150_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_1500022_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 150_22.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/3_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_30011_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 3_11.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/3_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_30012_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 3_12.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/3_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_30021_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 3_21.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/3_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_30022_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 3_22.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/21_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_210011_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 21_11.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/21_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_210012_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 21_12.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/21_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_210021_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 21_21.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/21_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_210022_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 21_22.las


./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/143_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_1430011_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 143_11.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/143_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_1430012_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 143_12.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/143_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_1430021_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 143_21.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/143_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_1430022_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 143_22.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/128_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_1280011_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 128_11.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/128_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_1280012_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 128_12.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/128_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_1280021_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 128_21.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/128_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_1280022_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 128_22.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/10_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_100011_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 10_11.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/10_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_100012_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 10_12.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/10_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_100021_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 10_21.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/10_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_100022_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 10_22.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/103_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_1030011_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 103_11.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/103_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_1030012_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 103_12.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/103_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_1030021_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 103_21.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/103_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_1030022_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 103_22.las


./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/101_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_1010011_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 101_11.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/101_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_1010012_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 101_12.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/101_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_1010021_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 101_21.las

./lasclip.sh -i "/media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/101_aligned.las" -poly /home/koomikko/Documents/UAV-ITD_s1.0_2.2/uav_itd_2.2/plot_1010022_seg.shp -cores 5 -odir /media/koomikko/B8C80A93C80A4FD41/id4points/LASutils/lasrelate_xy_test/all_point_clouds_collinear/ground_classified/dz/clipped/noisefree/clipped/ -o 101_22.las

